In [4]:
#adding 2 matrices using list
A=[[1,2,3]
   ,[4,5,6]
   ,[7,8,9]]
B=[[9,5,6]
  ,[4,5,9]
  ,[2,4,7]]
C=[[0,0,0]
  ,[0,0,0]
  ,[0,0,0]]

for i in range(len(A)):
    for j in range(len(A[0])):
     C[i][j]=A[i][j]+B[i][j]

for row in C:
    print(row)

[10, 7, 9]
[8, 10, 15]
[9, 12, 16]


In [5]:
#adding 2 matrices using numpy
import numpy as np
a=np.array([[1,2,3],[2,6,9],[5,8,1]])
b=np.array([[1,6,4],[0,5,9],[7,3,1]])
result=a+b
print(result)

[[ 2  8  7]
 [ 2 11 18]
 [12 11  2]]
